# All donations are appreciated and will go to fund for my Master's degree to turn this dream into a reality. Thank you, friends!

github: https://github.com/sponsors/qikevinl
thanks_dev: https://thanks.dev/e/gh/qikevinl
patreon: https://www.patreon.com/posts/149195350?pr=true
buy_me_a_coffee: https://buymeacoffee.com/qikevinl
