# I really don't spend money these days. All contributions will be stricly to help pay for post-graduate's. It's the next logical step to get emmersed in what I love most.

github: qikevinl
thanks_dev: u/gh/qikevinl
patreon: qikevinl
buy_me_a_coffee: qikevinl
