"""
Bubble Sort Visualization
Generated by LearnViz
"""
from manim import *

class SortingScene(Scene):
    def construct(self):
        array = [64, 34, 25, 12, 22, 11, 90]
        n = len(array)

        # Title
        title = Text("Bubble Sort", font_size=48)
        self.play(Write(title))
        self.wait(1)
        self.play(title.animate.to_edge(UP).scale(0.6))

        # Create bars
        bars = self.create_bars(array)
        self.play(Create(bars))
        self.wait(1)

        # Sort with animation
        self.bubble_sort(bars, array)

        # Done
        done_text = Text("Sorted!", font_size=36, color=GREEN)
        done_text.to_edge(DOWN)
        self.play(Write(done_text))
        self.play(bars.animate.set_color(GREEN))
        self.wait(2)

    def create_bars(self, array):
        bars = VGroup()
        max_val = max(array)
        bar_width = 0.8
        spacing = 0.9

        for i, val in enumerate(array):
            height = (val / max_val) * 4
            bar = Rectangle(
                width=bar_width,
                height=height,
                fill_opacity=0.7,
                fill_color=BLUE,
                stroke_color=WHITE
            )
            bar.move_to(
                LEFT * (len(array) / 2 - i) * spacing + DOWN * (2 - height / 2)
            )

            # Value label
            label = Text(str(val), font_size=16)
            label.next_to(bar, UP, buff=0.1)
            bar.label = label

            bars.add(VGroup(bar, label))

        return bars

    def swap_bars(self, bars, i, j):
        bar_i, bar_j = bars[i], bars[j]
        pos_i, pos_j = bar_i.get_center(), bar_j.get_center()

        self.play(
            bar_i.animate.set_color(RED),
            bar_j.animate.set_color(RED),
            run_time=0.3
        )
        self.play(
            bar_i.animate.move_to([pos_j[0], bar_i.get_center()[1], 0]),
            bar_j.animate.move_to([pos_i[0], bar_j.get_center()[1], 0]),
            run_time=0.5
        )
        self.play(
            bar_i.animate.set_color(BLUE),
            bar_j.animate.set_color(BLUE),
            run_time=0.3
        )

        # Swap in list
        bars[i], bars[j] = bars[j], bars[i]

    def bubble_sort(self, bars, array):
        n = len(array)
        for i in range(n):
            for j in range(0, n - i - 1):
                # Highlight comparison
                self.play(
                    bars[j].animate.set_color(YELLOW),
                    bars[j + 1].animate.set_color(YELLOW),
                    run_time=0.2
                )

                if array[j] > array[j + 1]:
                    self.swap_bars(bars, j, j + 1)
                    array[j], array[j + 1] = array[j + 1], array[j]
                else:
                    self.play(
                        bars[j].animate.set_color(BLUE),
                        bars[j + 1].animate.set_color(BLUE),
                        run_time=0.2
                    )

    def selection_sort(self, bars, array):
        n = len(array)
        for i in range(n):
            min_idx = i
            self.play(bars[i].animate.set_color(PURPLE), run_time=0.2)

            for j in range(i + 1, n):
                self.play(bars[j].animate.set_color(YELLOW), run_time=0.1)
                if array[j] < array[min_idx]:
                    if min_idx != i:
                        self.play(bars[min_idx].animate.set_color(BLUE), run_time=0.1)
                    min_idx = j
                    self.play(bars[min_idx].animate.set_color(RED), run_time=0.1)
                else:
                    self.play(bars[j].animate.set_color(BLUE), run_time=0.1)

            if min_idx != i:
                self.swap_bars(bars, i, min_idx)
                array[i], array[min_idx] = array[min_idx], array[i]

            self.play(bars[i].animate.set_color(GREEN), run_time=0.2)

    def insertion_sort(self, bars, array):
        for i in range(1, len(array)):
            key = array[i]
            self.play(bars[i].animate.set_color(YELLOW), run_time=0.2)

            j = i - 1
            while j >= 0 and array[j] > key:
                self.swap_bars(bars, j, j + 1)
                array[j + 1] = array[j]
                j -= 1

            array[j + 1] = key
            self.play(bars[j + 1].animate.set_color(BLUE), run_time=0.2)


if __name__ == "__main__":
    pass
