"""
Binary Search Visualization
Generated by LearnViz
"""
from manim import *

class BinarySearchScene(Scene):
    def construct(self):
        # Configuration
        array = [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
        target = 7

        # Title
        title = Text("Binary Search Algorithm", font_size=48)
        subtitle = Text(f"Finding {target} in a sorted array", font_size=24)
        subtitle.next_to(title, DOWN)

        self.play(Write(title))
        self.play(FadeIn(subtitle))
        self.wait(1)
        self.play(FadeOut(title), FadeOut(subtitle))

        # Create array visualization
        boxes = VGroup()
        numbers = VGroup()
        indices = VGroup()

        for i, val in enumerate(array):
            box = Square(side_length=0.8)
            box.set_stroke(WHITE, 2)
            num = Text(str(val), font_size=24)
            idx = Text(str(i), font_size=16, color=GRAY)

            if i > 0:
                box.next_to(boxes[-1], RIGHT, buff=0.1)

            num.move_to(box.get_center())
            idx.next_to(box, DOWN, buff=0.1)

            boxes.add(box)
            numbers.add(num)
            indices.add(idx)

        array_group = VGroup(boxes, numbers, indices)
        array_group.center()

        # Target display
        target_text = Text(f"Target: {target}", font_size=32)
        target_text.to_edge(UP)

        self.play(
            Create(boxes),
            Write(numbers),
            Write(indices),
            Write(target_text)
        )
        self.wait(1)

        # Binary search animation
        left, right = 0, len(array) - 1
        step = 1

        # Pointers
        left_arrow = Arrow(start=DOWN, end=UP, color=BLUE).scale(0.5)
        right_arrow = Arrow(start=DOWN, end=UP, color=RED).scale(0.5)
        left_label = Text("L", font_size=20, color=BLUE)
        right_label = Text("R", font_size=20, color=RED)

        left_arrow.next_to(boxes[left], DOWN, buff=0.5)
        right_arrow.next_to(boxes[right], DOWN, buff=0.5)
        left_label.next_to(left_arrow, DOWN, buff=0.1)
        right_label.next_to(right_arrow, DOWN, buff=0.1)

        self.play(
            Create(left_arrow), Write(left_label),
            Create(right_arrow), Write(right_label)
        )

        while left <= right:
            mid = (left + right) // 2

            # Step indicator
            step_text = Text(f"Step {step}: Check middle (index {mid})", font_size=24)
            step_text.to_edge(DOWN)
            self.play(Write(step_text))

            # Highlight middle
            self.play(boxes[mid].animate.set_fill(YELLOW, opacity=0.5))
            self.wait(0.5)

            if array[mid] == target:
                # Found!
                found_text = Text(f"Found {target} at index {mid}!", font_size=32, color=GREEN)
                found_text.next_to(step_text, UP)
                self.play(
                    boxes[mid].animate.set_fill(GREEN, opacity=0.7),
                    Write(found_text)
                )
                break
            elif array[mid] < target:
                # Go right
                compare_text = Text(f"{array[mid]} < {target}, search right half", font_size=20)
                compare_text.next_to(step_text, UP)
                self.play(Write(compare_text))

                # Gray out left half
                for i in range(left, mid + 1):
                    self.play(
                        boxes[i].animate.set_fill(GRAY, opacity=0.3),
                        run_time=0.2
                    )

                left = mid + 1
                left_arrow.generate_target()
                left_arrow.target.next_to(boxes[left] if left < len(array) else boxes[-1], DOWN, buff=0.5)
                left_label.generate_target()
                left_label.target.next_to(left_arrow.target, DOWN, buff=0.1)
                self.play(
                    MoveToTarget(left_arrow),
                    MoveToTarget(left_label)
                )
                self.play(FadeOut(compare_text))
            else:
                # Go left
                compare_text = Text(f"{array[mid]} > {target}, search left half", font_size=20)
                compare_text.next_to(step_text, UP)
                self.play(Write(compare_text))

                # Gray out right half
                for i in range(mid, right + 1):
                    self.play(
                        boxes[i].animate.set_fill(GRAY, opacity=0.3),
                        run_time=0.2
                    )

                right = mid - 1
                right_arrow.generate_target()
                right_arrow.target.next_to(boxes[right] if right >= 0 else boxes[0], DOWN, buff=0.5)
                right_label.generate_target()
                right_label.target.next_to(right_arrow.target, DOWN, buff=0.1)
                self.play(
                    MoveToTarget(right_arrow),
                    MoveToTarget(right_label)
                )
                self.play(FadeOut(compare_text))

            self.play(boxes[mid].animate.set_fill(WHITE, opacity=0))
            self.play(FadeOut(step_text))
            step += 1

        self.wait(2)


if __name__ == "__main__":
    # Render with: manim -pql binary_search.py BinarySearchScene
    pass
