"""
Pythagorean Theorem Visualization
Generated by LearnViz
"""
from manim import *

class PythagoreanScene(Scene):
    def construct(self):
        # Title
        title = Text("The Pythagorean Theorem", font_size=48)
        self.play(Write(title))
        self.wait(1)
        self.play(title.animate.to_edge(UP).scale(0.6))

        # Create right triangle
        a, b = 2, 1.5  # sides
        c = np.sqrt(a**2 + b**2)  # hypotenuse

        triangle = Polygon(
            ORIGIN,
            RIGHT * a,
            RIGHT * a + UP * b,
            fill_opacity=0.3,
            fill_color=BLUE,
            stroke_color=WHITE
        )
        triangle.move_to(ORIGIN)

        # Labels
        a_label = MathTex("a").next_to(triangle, DOWN)
        b_label = MathTex("b").next_to(triangle, RIGHT)
        c_label = MathTex("c").move_to(triangle.get_center() + UP * 0.5 + LEFT * 0.5)

        # Right angle marker
        right_angle = RightAngle(
            Line(ORIGIN, RIGHT * a),
            Line(RIGHT * a, RIGHT * a + UP * b),
            length=0.2
        )

        self.play(Create(triangle))
        self.play(Write(a_label), Write(b_label), Write(c_label))
        self.play(Create(right_angle))
        self.wait(1)

        # Create squares on each side
        sq_a = Square(side_length=a, fill_opacity=0.5, fill_color=RED)
        sq_a.next_to(triangle, DOWN, buff=0)

        sq_b = Square(side_length=b, fill_opacity=0.5, fill_color=GREEN)
        sq_b.next_to(triangle, RIGHT, buff=0)

        sq_c = Square(side_length=c, fill_opacity=0.5, fill_color=YELLOW)
        # Position c square on hypotenuse (simplified positioning)
        sq_c.rotate(np.arctan(b/a))
        sq_c.move_to(triangle.get_center() + UP * 1.5 + LEFT * 1)

        # Area labels
        a2_label = MathTex("a^2", color=RED).move_to(sq_a.get_center())
        b2_label = MathTex("b^2", color=GREEN).move_to(sq_b.get_center())
        c2_label = MathTex("c^2", color=YELLOW).move_to(sq_c.get_center())

        self.play(
            Create(sq_a), Write(a2_label),
            Create(sq_b), Write(b2_label),
            run_time=2
        )
        self.wait(1)

        self.play(Create(sq_c), Write(c2_label), run_time=2)
        self.wait(1)

        # Show the equation
        equation = MathTex("a^2", "+", "b^2", "=", "c^2", font_size=56)
        equation.to_edge(DOWN)
        equation[0].set_color(RED)
        equation[2].set_color(GREEN)
        equation[4].set_color(YELLOW)

        self.play(Write(equation))
        self.wait(1)

        # Highlight equation
        box = SurroundingRectangle(equation, color=WHITE, buff=0.2)
        self.play(Create(box))
        self.wait(2)


if __name__ == "__main__":
    pass
