"""
Synaptic Transmission
Generated by LearnViz

Visualizes how signals cross from one neuron to another.
Features: Text management to prevent overlaps, detailed explanations.
"""
from manim import *


class TextManager:
    """Manages text display to prevent overlaps."""

    def __init__(self, scene):
        self.scene = scene
        self.active_texts = {}
        self.regions = {
            "title": UP * 3.5,
            "top": UP * 3.0,
            "bottom": DOWN * 3.3,
            "center": ORIGIN,
        }

    def show(self, text: str, region: str = "bottom", font_size: int = 22,
             color=WHITE, duration: float = 0.5) -> Text:
        """Display text in a region, clearing existing text there first."""
        if region in self.active_texts:
            self.scene.play(FadeOut(self.active_texts[region]), run_time=0.2)

        text_obj = Text(text, font_size=font_size, color=color)
        text_obj.move_to(self.regions.get(region, ORIGIN))

        # Scale if too wide
        if text_obj.width > 13:
            text_obj.scale(13 / text_obj.width)

        self.scene.play(Write(text_obj), run_time=duration)
        self.active_texts[region] = text_obj
        return text_obj

    def clear(self, region: str = None):
        """Clear text from region(s)."""
        if region and region in self.active_texts:
            self.scene.play(FadeOut(self.active_texts[region]), run_time=0.2)
            del self.active_texts[region]
        elif region is None:
            if self.active_texts:
                self.scene.play(*[FadeOut(t) for t in self.active_texts.values()], run_time=0.3)
                self.active_texts.clear()


class SynapseScene(Scene):
    def construct(self):
        self.tm = TextManager(self)

        # Introduction
        self.show_intro()

        # Build and explain synapse structure
        self.create_synapse()
        self.wait(1)

        # Signal arrival
        self.signal_arrives()
        self.wait(0.5)

        # Vesicle release with explanation
        self.release_neurotransmitters()
        self.wait(0.5)

        # Receptor binding
        self.receptor_binding()

        # Conclusion
        self.show_conclusion()
        self.wait(2)

    def show_intro(self):
        """Introduction with clear explanation."""
        title = Text("Synaptic Transmission", font_size=48)
        subtitle = Text("How neurons communicate with each other", font_size=24, color=GRAY)
        subtitle.next_to(title, DOWN, buff=0.3)

        self.play(Write(title))
        self.play(FadeIn(subtitle))
        self.wait(1.5)

        # Educational context
        intro_text = Text(
            "Neurons don't physically touch - they communicate\n"
            "across tiny gaps called synapses using chemicals.",
            font_size=20, color=BLUE_B
        )
        intro_text.next_to(subtitle, DOWN, buff=0.5)
        self.play(FadeIn(intro_text))
        self.wait(2)

        self.play(FadeOut(title), FadeOut(subtitle), FadeOut(intro_text))

    def create_synapse(self):
        """Create synapse structure with labeled components."""
        # Explanation text at bottom
        self.tm.show(
            "The synapse has three main parts: presynaptic terminal, synaptic cleft, and postsynaptic membrane",
            region="bottom", font_size=20, color=BLUE_B
        )

        # Presynaptic terminal (top) - shifted up to make room
        self.presynaptic = RoundedRectangle(
            width=5, height=2.2, corner_radius=0.3,
            fill_opacity=0.6, fill_color=BLUE, stroke_color=WHITE, stroke_width=2
        ).shift(UP * 1.8)

        pre_label = Text("Presynaptic Terminal", font_size=16, color=BLUE_B)
        pre_label.next_to(self.presynaptic, LEFT, buff=0.2)

        # Vesicles inside presynaptic - clearly visible
        self.vesicles = VGroup()
        vesicle_label_added = False
        for i in range(6):
            vesicle = Circle(radius=0.18, fill_opacity=0.9, fill_color=YELLOW, stroke_color=ORANGE, stroke_width=2)
            vesicle.move_to(self.presynaptic.get_center() + UP * 0.4 + LEFT * 1.2 + RIGHT * i * 0.45)
            self.vesicles.add(vesicle)

        vesicle_label = Text("Vesicles (contain\nneurotransmitters)", font_size=12, color=YELLOW)
        vesicle_label.next_to(self.vesicles, RIGHT, buff=0.3)

        # Synaptic cleft (gap) - make it more visible
        self.cleft = Rectangle(
            width=5.5, height=0.6,
            fill_opacity=0.15, fill_color=WHITE, stroke_color=GRAY, stroke_width=1
        )
        cleft_label = Text("Synaptic Cleft (~20nm gap)", font_size=14, color=GRAY)
        cleft_label.next_to(self.cleft, RIGHT, buff=0.2)

        # Postsynaptic membrane (bottom)
        self.postsynaptic = RoundedRectangle(
            width=5, height=1.8, corner_radius=0.3,
            fill_opacity=0.6, fill_color=GREEN, stroke_color=WHITE, stroke_width=2
        ).shift(DOWN * 1.8)

        post_label = Text("Postsynaptic Neuron", font_size=16, color=GREEN_B)
        post_label.next_to(self.postsynaptic, LEFT, buff=0.2)

        # Receptors on postsynaptic membrane - more prominent
        self.receptors = VGroup()
        for i in range(5):
            receptor = Rectangle(width=0.25, height=0.5, fill_opacity=0.9, fill_color=RED, stroke_color=WHITE, stroke_width=1)
            receptor.move_to(self.postsynaptic.get_top() + UP * 0.1 + LEFT * 1 + RIGHT * i * 0.55)
            self.receptors.add(receptor)

        receptor_label = Text("Receptors", font_size=12, color=RED)
        receptor_label.next_to(self.receptors, LEFT, buff=0.2).shift(UP * 0.2)

        # Animate construction with explanations
        self.play(Create(self.presynaptic), Write(pre_label), run_time=1)
        self.play(Create(self.vesicles), Write(vesicle_label), run_time=1)

        self.tm.show(
            "Vesicles are small spheres filled with neurotransmitter molecules",
            region="bottom", font_size=20, color=YELLOW
        )
        self.wait(1.5)

        self.play(Create(self.cleft), Write(cleft_label), run_time=0.8)

        self.tm.show(
            "The synaptic cleft is a tiny gap - only about 20 nanometers wide",
            region="bottom", font_size=20, color=GRAY
        )
        self.wait(1.5)

        self.play(Create(self.postsynaptic), Write(post_label), run_time=1)
        self.play(Create(self.receptors), Write(receptor_label), run_time=0.8)

        self.tm.show(
            "Receptors are proteins that recognize specific neurotransmitters",
            region="bottom", font_size=20, color=RED
        )
        self.wait(1.5)

        # Store labels for later reference
        self.structure_labels = VGroup(pre_label, vesicle_label, cleft_label, post_label, receptor_label)

    def signal_arrives(self):
        """Action potential arrives with explanation."""
        self.tm.show(
            "Step 1: An action potential arrives at the presynaptic terminal",
            region="bottom", font_size=22, color=YELLOW
        )

        # Visual indicator of signal arriving
        signal_arrow = Arrow(
            start=self.presynaptic.get_left() + LEFT * 1.5,
            end=self.presynaptic.get_left(),
            color=YELLOW, stroke_width=4
        )
        signal_label = Text("Action\nPotential", font_size=14, color=YELLOW)
        signal_label.next_to(signal_arrow, UP, buff=0.1)

        self.play(Create(signal_arrow), Write(signal_label), run_time=0.8)

        # Flash the presynaptic terminal
        self.play(
            self.presynaptic.animate.set_fill(YELLOW, opacity=0.8),
            Flash(self.presynaptic.get_center(), color=YELLOW, line_length=0.3, num_lines=12),
            run_time=0.6
        )
        self.play(
            self.presynaptic.animate.set_fill(BLUE, opacity=0.6),
            run_time=0.4
        )

        self.tm.show(
            "This triggers calcium ions to enter, causing vesicles to move toward the membrane",
            region="bottom", font_size=20, color=BLUE_B
        )
        self.wait(1.5)

        self.play(FadeOut(signal_arrow), FadeOut(signal_label), run_time=0.3)

    def release_neurotransmitters(self):
        """Vesicle fusion and neurotransmitter release with detailed explanation."""
        self.tm.show(
            "Step 2: Vesicles fuse with the membrane and release neurotransmitters",
            region="bottom", font_size=22, color=ORANGE
        )

        # Neurotransmitters released
        self.neurotransmitters = VGroup()

        for i, vesicle in enumerate(self.vesicles[:3]):
            # Move vesicle to membrane
            target_pos = self.presynaptic.get_bottom() + RIGHT * (i - 1) * 0.8
            self.play(vesicle.animate.move_to(target_pos), run_time=0.4)

            # Vesicle "opens" - change appearance
            self.play(vesicle.animate.set_stroke(color=WHITE, width=3), run_time=0.2)

            # Release neurotransmitters
            for j in range(4):
                nt = Dot(radius=0.08, color=YELLOW)
                nt.move_to(vesicle.get_center())
                self.neurotransmitters.add(nt)

                # Scatter into cleft
                target = self.cleft.get_center() + LEFT * 0.8 + RIGHT * (i * 1.2 + j * 0.25) + UP * 0.1 * (j % 2)
                self.add(nt)
                self.play(nt.animate.move_to(target), run_time=0.15)

            # Fade vesicle (recycled)
            self.play(FadeOut(vesicle), run_time=0.2)

        self.tm.show(
            "Thousands of neurotransmitter molecules are released in microseconds",
            region="bottom", font_size=20, color=YELLOW
        )
        self.wait(1.5)

    def receptor_binding(self):
        """Neurotransmitters bind to receptors with explanation."""
        self.tm.show(
            "Step 3: Neurotransmitters diffuse across and bind to receptors",
            region="bottom", font_size=22, color=GREEN
        )

        # Move neurotransmitters to receptors
        for i, nt in enumerate(self.neurotransmitters[:5]):
            if i < len(self.receptors):
                target = self.receptors[i].get_top() + UP * 0.05
                self.play(nt.animate.move_to(target), run_time=0.25)
                # Receptor activates - color change
                self.play(
                    self.receptors[i].animate.set_fill(YELLOW, opacity=0.95),
                    run_time=0.2
                )

        self.wait(0.5)
        self.tm.show(
            "Receptor activation opens ion channels, allowing the signal to continue",
            region="bottom", font_size=20, color=GREEN
        )

        # Postsynaptic response
        self.play(
            self.postsynaptic.animate.set_fill(YELLOW, opacity=0.6),
            Flash(self.postsynaptic.get_center(), color=GREEN, line_length=0.2, num_lines=8),
            run_time=0.5
        )
        self.play(
            self.postsynaptic.animate.set_fill(GREEN, opacity=0.6),
            run_time=0.3
        )

        self.wait(1)

    def show_conclusion(self):
        """Wrap up with key takeaways."""
        self.tm.clear()

        # Fade structure slightly
        self.play(
            self.presynaptic.animate.set_opacity(0.4),
            self.postsynaptic.animate.set_opacity(0.4),
            self.cleft.animate.set_opacity(0.1),
            self.structure_labels.animate.set_opacity(0.4),
            run_time=0.5
        )

        # Summary box
        summary = VGroup(
            Text("Synaptic Transmission Summary", font_size=24, color=WHITE),
            Text("1. Action potential triggers calcium influx", font_size=18, color=YELLOW),
            Text("2. Vesicles fuse and release neurotransmitters", font_size=18, color=ORANGE),
            Text("3. Neurotransmitters bind to receptors", font_size=18, color=GREEN),
            Text("4. Ion channels open, signal continues", font_size=18, color=BLUE),
        ).arrange(DOWN, aligned_edge=LEFT, buff=0.25)

        box = SurroundingRectangle(summary, color=WHITE, buff=0.3, corner_radius=0.1)
        summary_group = VGroup(box, summary)
        summary_group.move_to(ORIGIN)

        self.play(Create(box), Write(summary), run_time=2)
        self.wait(2)

        # Final message
        final = Text("This process occurs billions of times per second in your brain!", font_size=20, color=BLUE_B)
        final.next_to(summary_group, DOWN, buff=0.5)
        self.play(FadeIn(final))


if __name__ == "__main__":
    # Render with: manim -pql synapse.py SynapseScene
    pass
